server:
  port: 8771

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer2
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/



management.security.enabled: false