server:
  port: 8781

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 192.168.76.162
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.76.162:8771/eureka/,http://192.168.76.162:8761/eureka/,http://192.168.76.162:8781/eureka/
  server:
    eviction-interval-timer-in-ms: 30000


management.security.enabled: false