spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VelementsMount/springcloud.git
          username: VelementsMount
          password: lzl640,lzl640
#          basedir: /tmp/config_repo
#          cloneOnStart: true
#          force-pull: true
          search-paths: configurations/{application}
server:
  port: 8808
encrypt:
  key: liuzhilin
#encrypt:
#  keyStore:
#    location: classpath:/server.jks
#    password: letmein
#    alias: mytestkey
#    secret: changeme
management:
  security:
    enabled: false
security:
  basic:
    enabled: true
  user:
    name: liuzhilin
    password: liuzhilin

eureka:
  instance:
    hostname: peer1
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8771/eureka/


