spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VelementsMount/springcloud.git
          username: VelementsMount
          password: lzl640,lzl640
          search-paths: configurations
server:
  port: 8808

