eureka:
  instance:
    hostname: peer1
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8771/eureka/
server:
  port: 8888

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
spring:
  application:
    name: service-hi
  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
  ConnectTimeout: 100
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true

service_hello.ribbon.listOfServers:


