server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer1
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://peer2:8771/eureka/



management.security.enabled: false