eureka:
  instance:
    hostname: peer2
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8771/eureka/
server:
  port: 8090
spring:
  application:
    name: service-hello